// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuEWBFHmNOoWBf9HYr05YKzooiu45kA-Y',
    appId: '1:36676984814:web:e5d563c5a8163869f3b8ff',
    messagingSenderId: '36676984814',
    projectId: 'online-homebakery',
    authDomain: 'online-homebakery.firebaseapp.com',
    storageBucket: 'online-homebakery.appspot.com',
    measurementId: 'G-MJ1L1HG9L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbqEYrnpElDLIwhqd3oFfwMaiS2nQdFMM',
    appId: '1:36676984814:android:088ef7705a2a53c7f3b8ff',
    messagingSenderId: '36676984814',
    projectId: 'online-homebakery',
    storageBucket: 'online-homebakery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH1vHE94PXfd-4UzFH2oXl7ba7VQR9JKc',
    appId: '1:36676984814:ios:30aec4085d849699f3b8ff',
    messagingSenderId: '36676984814',
    projectId: 'online-homebakery',
    storageBucket: 'online-homebakery.appspot.com',
    iosClientId: '36676984814-0n5a40lsd9jk99g0v79p2td2vhd2h9hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nihaljumailamrathaju',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH1vHE94PXfd-4UzFH2oXl7ba7VQR9JKc',
    appId: '1:36676984814:ios:30aec4085d849699f3b8ff',
    messagingSenderId: '36676984814',
    projectId: 'online-homebakery',
    storageBucket: 'online-homebakery.appspot.com',
    iosClientId: '36676984814-0n5a40lsd9jk99g0v79p2td2vhd2h9hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nihaljumailamrathaju',
  );
}
